### ISSUE TITLE
SSL certificate duration option declared as a interpolated variable?

### ISSUE THREAD

**Issue by kinjelom** [cloudfoundry/jumpbox-deployment#29]
Now it is not easy to change the duration of all generated certificates because one bosh operation (ops file) must match exactly one item of variables array:
```
Parsing release set manifest 'jumpbox.yml':
  Evaluating manifest:
    Expected to find exactly one matching array item for path '/variables/type=certificate' 
```

Something like that would be great:
```
variables:
- name: default_ca
  type: certificate
  options:
    common_name: ca
    is_ca: true
    duration: ((certificate_duration))
```

https://github.com/cloudfoundry/bosh-deployment/issues/365
